del src\gervill\com\sun\media\sound\AiffFileFormat.java
del src\gervill\com\sun\media\sound\AiffFileReader.java
del src\gervill\com\sun\media\sound\AiffFileWriter.java
del src\gervill\com\sun\media\sound\AlawCodec.java
del src\gervill\com\sun\media\sound\AuFileFormat.java
del src\gervill\com\sun\media\sound\AuFileReader.java
del src\gervill\com\sun\media\sound\AuFileWriter.java
del src\gervill\com\sun\media\sound\AudioFileSoundbankReader.java
del src\gervill\com\sun\media\sound\AudioFloatFormatConverter.java
del src\gervill\com\sun\media\sound\DLSSoundbankReader.java
del src\gervill\com\sun\media\sound\DataPusher.java
del src\gervill\com\sun\media\sound\JARSoundbankReader.java
del src\gervill\com\sun\media\sound\JavaSoundAudioClip.java
del src\gervill\com\sun\media\sound\MidiOutDeviceProvider.java
del src\gervill\com\sun\media\sound\ModelAbstractChannelMixer.java
del src\gervill\com\sun\media\sound\ModelAbstractOscillator.java
del src\gervill\com\sun\media\sound\ModelStandardDirector.java
del src\gervill\com\sun\media\sound\PCMtoPCMCodec.java
del src\gervill\com\sun\media\sound\RealTimeSequencer.java
del src\gervill\com\sun\media\sound\RealTimeSequencerProvider.java
del src\gervill\com\sun\media\sound\SF2SoundbankReader.java
del src\gervill\com\sun\media\sound\SimpleInstrument.java
del src\gervill\com\sun\media\sound\SimpleSoundbank.java
del src\gervill\com\sun\media\sound\SoftMidiAudioFileReader.java
del src\gervill\com\sun\media\sound\SoftProvider.java
del src\gervill\com\sun\media\sound\SoftShortMessage.java
del src\gervill\com\sun\media\sound\StandardMidiFileReader.java
del src\gervill\com\sun\media\sound\StandardMidiFileWriter.java
del src\gervill\com\sun\media\sound\SunCodec.java
del src\gervill\com\sun\media\sound\SunFileReader.java
del src\gervill\com\sun\media\sound\SunFileWriter.java
del src\gervill\com\sun\media\sound\UlawCodec.java
del src\gervill\com\sun\media\sound\WaveExtensibleFileReader.java
del src\gervill\com\sun\media\sound\WaveFileFormat.java
del src\gervill\com\sun\media\sound\WaveFileReader.java
del src\gervill\com\sun\media\sound\WaveFileWriter.java
del src\gervill\com\sun\media\sound\WaveFloatFileReader.java
del src\gervill\com\sun\media\sound\WaveFloatFileWriter.java
del src\gervill\java\applet\AudioClip.java
del src\gervill\javax\sound\sampled\EnumControl.java
del src\gervill\javax\sound\sampled\ReverbType.java